### ISSUE TITLE
Player  "No Show Found"

### ISSUE THREAD

**Issue by radiorob** [openbroadcaster/obplayer#10]
Less and Less this reveals itself

An issue where "no show found" to play schedule on player. Usually fixes itself top of hour.

Reset and clear through DB reset in OBPlayer dashboard

**Comment by geoplanet** [comment]
- Does this occur after a start-up, or does it fail after some period of correct scheduling?
 - Is this workaround adequate, or is there still an issue to resolve?

**Comment by radiorob** [comment]
It is still an underlying issue, rarely shows up, but still there. When 
it does happen, restarting doesn't clear it

On 16-05-24 10:03 AM, geoplanet wrote:
>
>   * Does this occur after a start-up, or does it fail after some
>     period of correct scheduling?
>   * Is this workaround adequate, or is there still an issue to resolve?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/openbroadcaster/obplayer/issues/10#issuecomment-221337064>
>

-- 
*Robert G. Hopkins*

*Radio Enthusiast*

Box 87, Tagish, Yukon, Y0B1TO, Canada

Office: 867-667-6397

www.openbroadcaster.pro/rob-hopkins 
<https://openbroadcaster.pro/rob-hopkins>
OpenBroadcaster Inc.

**Comment by geoplanet** [comment]
This issue was moved to openbroadcaster/Player#13
