### ISSUE TITLE
Adding Private flagged media to Playlist

### ISSUE THREAD

**Issue by radiorob** [openbroadcaster/obplayer#11]
Even if you are an admin, you can't take a private media item and put it in a playlist owned by someone else.

This is a hassle, Admin users create PL and when trying to Save, get message "can't add private media"  There are no indicators what is marked as Private media

The reason is that it would create a mess.

For example, John uploads some private media.

Sally (basic user) creates a playlist.

Jake (admin user) decides to add some of John's private media to Sally's playlist.

Sally goes to edit the playlist and then... what? Sally doesn't have access to even know about John's private media, let alone use it in a playlist.

Now if Jake wants to add private media to his own playlist, then that solves the problem. That is, until Jake loses his admin privileges. Now Jake has a playlist with John's private media and he doesn't have permission to access it. Same issue.

So the rule is... you can't add private media to a playlist other than playlists owned by the same user as the media.

**Comment by transistorfet** [comment]
This issue was moved to openbroadcaster/observer#1
