### ISSUE TITLE
Toggle recordings on/off in the obplayer

### ISSUE THREAD

**Issue by radiorob** [openbroadcaster/obplayer#125]
Presently obplayer records and uploads live recording back to server. Input is analog line plugged into the 3.5mm jack and through silence detection.  

End user left the Mic on for more than 2 months. So as designed, OB did silence detection and uploaded recordings to the server.

Wonder if Maintenance Mode would solve this, or add "also pause line in capture.  Toggling this function would override everything and play FB media which is what it is supposed to do?

**Comment by ltyndale** [comment]
This issue sounds more like a user error as opposed to something to 
chase down.  When a mic is left on, it is left on.

But with that in mind, most automation systems can monitor a GPI from 
one of the many systems that can do GPIO's.  Whether that is the 
Broadcast Tools units, SAS routing switchers, or something else (or even 
the inputs on a serial or parallel port).  Then tie the logic output on 
a mic channel from a console to the input logic in the playout / 
automation system to toggle on / off the record (or whatever else you 
want to toggle on or off).  It can provide a little better control then 
just silence detection which - if you end up with something like a 
ground hum or other noise coming out of a mic pre-amp or processor, that 
could really confuse silence detection.

On 2024-02-20 16:09, Rob Hopkins wrote:

> Presently obplayer records and uploads live recording back to server. 
> Input is analog line plugged into the 3.5mm jack and through silence 
> detection.
> 
> End user left the Mic on for more than 2 months. So as designed, OB did 
> silence detection and uploaded recordings to the server.
> 
> Wonder if Maintenance Mode would solve this, or add "also pause line in 
> capture. Toggling this function would override everything and play FB 
> media which is what it is supposed to do?
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you are subscribed to this 
> thread.Message ID: ***@***.***>


Links:
------
[1] https://github.com/openbroadcaster/obplayer/issues/125
[2]

**Comment by radiorob** [comment]
Can't fix user error
