### ISSUE TITLE
Line In audio is still present, even when unchecked in dashboard

### ISSUE THREAD

**Issue by radiorob** [openbroadcaster/obplayer#20]
Noticed this on CFET.  Line In scheduler works even if this source is disabled.

**Comment by transistorfet** [comment]
That is correct.  The Line-in enable/disable setting is for the request source, which issues requests for the line-in to play when nothing else is able to play, but it does not disable the line-in audio input, which can still be scheduled to play by another request source (such as the sync/scheduler).  The other request sources, such as test signal, RTP, and RTSP are the same, in that disabling the source will prevent it from being scheduled based on priority, but the input is still available to play.  For example, disabling the RTP source will prevent it from playing when the nothing else is playing (such that it would play the line-in or test signal instead), but it will still be able to use the RTP source for the local streamer program from the live assist.
