### ISSUE TITLE
Ad Manager: Unable to see changes made

### ISSUE THREAD

**Issue by billpolonsky** [openbroadcaster/obplayer#22]
Mac Problem??

using eldorado

Unable to see changes made on ad manager using latest Chrome browser on my iMac. See italics 

_Chrome on my Mac: does not display items even though I can add them (Can't see them but they are there)
Safari on my Mac: Shows all items and can add and delete.
Firefox on my Mac: Shows all Items and can add and delete_

Tried my account on a Dell laptop running xubuntu 16.04 
_Chromium Browser: Able to fully use Ad Manager
Firefox Browser: Able to fully use Ad Manager_

FYI have no access to another Mac to see if this is reproducible.

**Comment by radiorob** [comment]
Have seen this in a Mac user with 10.12.2 Sierra.  After updates to OS and Chrome issue goes away.  Seen this go away with updates
