### ISSUE TITLE
Lack of Documentation - How to Link obplayer to observer

### ISSUE THREAD

**Issue by ScriptsByChris** [openbroadcaster/obplayer#23]
How do we link player to server?

**Comment by transistorfet** [comment]
The sync URL setting on the Sync tab of the player's dashboard is used to link to the server. It should be of the form "http://<ob-server-address>/remote.php" The device id and password settings on the same tab must correspond to the player settings on the server. The player will then attempt to connect to the server every minute or two to download the schedules and media.

The sync enable checkbox must be set and the player must be restarted for the changes to take effect. If you don't see the Sync tab, then on the Admin tab, you can click the Sync Tab checkbox and restart the player.

**Comment by ScriptsByChris** [comment]
Excellent! I'll try that! Thank you!

**Comment by radiorob** [comment]
We have a set of videos coming up that include advanced provisioning of player\server setup.  Keep any eye on our support.openbroadcaster.pro site and Youtube channel
