### ISSUE TITLE
LA media plays beyond show end time

### ISSUE THREAD

**Issue by qwaxw** [openbroadcaster/obplayer#28]
Live Assist: when media is playing whose duration extends beyond the scheduled end time of the show, the show does not end and the media continues playing beyond show end (next show on schedule does not start on time, or next show is overdubbed ie not heard until the LA media finishes playing), causing the next shows beginning not to be heard (ie join regular programming already in progress). Uncertain but LA screen may show 'override' and sometimes causes the next show to not display (override, no show playing).

**Comment by radiorob** [comment]
Thanks for reporting. Fixed
