### ISSUE TITLE
Missing Audio in CAP Alerts

### ISSUE THREAD

**Issue by UberPlexCa** [openbroadcaster/obplayer#36]
I'm using the current dev branch because AWS isn't working in the main on.  It seems to cut off the first 2.5 to 3 seconds of the alert tone as well as the first 2-3 seconds of the text to speech and I am not sure why.

**Comment by radiorob** [comment]
Pipeline issue when using onboard audio AND streaming at the same time. Fixed in new player 5.2.2 using gst-interpipe to manage pipes.
