### ISSUE TITLE
I don't see relay closure triggers or traffic logging

### ISSUE THREAD

**Issue by BD-Engineering** [openbroadcaster/obplayer#37]
Hello,

   Having looked at all of the documentation online I don't see traffic logging to reconcile invoices for advertisers..

   It would be required to be able to use for a commercial radio station.

   Also, what about using a GPI serial device to trigger local ad blocks during a live satellite program?

    From the online documentation it seems Open Broadcaster is only made for non-commercial stations that don't ever play live satellite programming that has local ad break signaling.

    Radio DJ has both of those things, and is what we currently use because it's easy enough for our dumb DJs that are baffled by real automation like AudioVault or Simian.

   Am I missing something, or is there actually a way to output as-run logs for just 1 advertiser, or even just for all advertisers so we can invoice them fairly?

    What about triggering short playlists based on relay closures sensed by something like a Broadcast Tools GPI-16?

I am hoping the online documentation is only lacking these details, and that they are already implemented.

Thanks,
AM

**Comment by radiorob** [comment]
It is possible to schedule an external feed from a Sat dish\Line in.  I have seen stations use this function to program a 2 minute news spot at top of hour.  There are a couple of ways to produce commercially acceptable playlogs\affidavits.  Admin>Player monitoring lets you see a log for dates/times with the ability to search for media ID of specific campaigns. There is a more advanced reporting tool designed to work with SoundExchange, producing properly formatted logs.  Both these methods allow export of CSV/XLS
