### ISSUE TITLE
Red Error [alerts] message on startup

### ISSUE THREAD

**Issue by radiorob** [openbroadcaster/obplayer#4]
Only happens on restart of application. Confirmed other users getting this (erroneous?) error message.  We shouldn't have anything RED unless a true error.  Why is this always red and only at the beginning?

UTC] [alerts] connected to alert broadcaster at streaming1.naad-adna.pelmorex.com:8080

**Comment by transistorfet** [comment]
All log messages marked [alerts] are assigned a red colour.  I can either change all [alerts] messages to another colour, or change the tag name of that one log message to something else.

**Comment by radiorob** [comment]
Change this first message tag to something like NADD Check in, Emergency 
Initialization, or even a [module] loading  module Emergency  sort of 
like the Module tag.

Our tech support, we advise to be on the look out for any red error 
messages.

Right then, we have red being used for 2 purposes, 1) for alerts 2) for 
error messages.

Would be OK to have red for both, as long as the first message is not 
RED to avoid confusion.

Rob

On 16-05-05 03:19 PM, transistor fet wrote:
>
> All log messages marked [alerts] are assigned a red colour. I can 
> either change all [alerts] messages to another colour, or change the 
> tag name of that one log message to something else.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/openbroadcaster/obplayer/issues/4#issuecomment-217296390>
>

-- 
*Robert G. Hopkins*

*Radio Enthusiast*

Box 87, Tagish, Yukon, Y0B1TO, Canada

Office: 867-667-6397

www.openbroadcaster.pro/rob-hopkins 
<https://openbroadcaster.pro/rob-hopkins>
OpenBroadcaster Inc.
