### ISSUE TITLE
add a simple check for improperly-formatted GEO codes

### ISSUE THREAD

**Issue by radiorob** [openbroadcaster/obplayer#5]
Do not allow spaces between SGC codes

Correct     1310
Incorrect   13  10

**Comment by transistorfet** [comment]
Do you mean give an error message if there are spaces between numbers?

**Comment by radiorob** [comment]
Correct, so that user is not able to enter incorrect formatting

**Comment by transistorfet** [comment]
Our latest code seems to already give an error when there are spaces between numbers (but not for spaces around commas)
