### ISSUE TITLE
Password System Bug

### ISSUE THREAD

**Issue by A-c0rN** [openbroadcaster/obplayer#51]
Error "AttributeError: module 'obplayer' has not attribute 'PasswordSystem'" on initial login

**To Reproduce**
1. Install OBPlayer from the GIT repo directly
2. run ./obplayer_check -f
3. Go to the WebServer and login using default creds
4. Should throw AttributeErrors in the console.

**Expected behavior**
Login and no AttributeErrors

 - OS: Ubuntu 20.04
 - Firefox 94.0

**Comment by vincentthedev** [comment]
Thank you for your report. This issue has since been fixed in the main branch.
