### ISSUE TITLE
youtube output choppy, gstreamer WARNs Got backwards dts! 

### ISSUE THREAD

**Issue by vaguelyr** [openbroadcaster/obplayer#58]
Hi,

**Describe the bug**

Youtube output is choppy/stuttery. Audio is fine. gstreamer WARN 'Got backwards dts! ' happens on the video pipeline, in flvmux, continuously. 

**To Reproduce**

GST_DEBUG=3 DISPLAY=:0 bash obplayer_loop  -d

**Expected behavior**

Youtube output is smooth. DTS shouldn't go backwards. 

**Desktop (please complete the following information):**
 
Player is running on Ubuntu 20.04.3 LTS
Observer running Debian GNU/Linux 11 (bullseye), installed with latest script

**Additional context**

GST_DEBUG=3 DISPLAY=:0 bash obplayer_loop  -d 1>out.txt 2>err.txt
out.txt : https://pastebin.com/y5jw83g8
err.txt : https://pastebin.com/b5w2VQV3
[out.txt](https://github.com/openbroadcaster/obplayer/files/7876219/out.txt)
[err.txt](https://github.com/openbroadcaster/obplayer/files/7876208/err.txt)

This is on a completely clean unmodified observer and obplayer. The obplayer is the branch from the Fix the Password Bug currently open pull request, since logging in is not possible otherwise. 

Observer has scheduled videos with sound, obplayer is playing the videos and streaming into youtube. Output is choppy. 

I want to make a generalized RTMP output but this existing issue derails that effort. If you could help me figure out where in the audio/video > flvmux > rtmpsink pipeline this issue is being caused, I could help fix it.

**Comment by alphabitnz** [comment]
> I want to make a generalized RTMP output but this existing issue derails that effort. If you could help me figure out where in the audio/video > flvmux > rtmpsink pipeline this issue is being caused, I could help fix it.

Vincent and I are currently developing a generalized RTMP module, it's still in development/testing but I have it fairly functional currently.

The main file to look at is obplayer/streamer/youtube.py, from 'Gst.ElementFactory.make('intervideosrc')'

I would be interested to know what output and streaming resolution settings you're using, and what CPU you're running on as the current production encoder settings are a) not offloaded to GPU and b) not particularly lightweight. Both of those issues are in scope of our work on the new RTMP module.

**Comment by alphabitnz** [comment]
@vaguelyr you can try the rtmp-changes branch which should have a lot better performance and control of Youtube/RTMP streaming. I'm going to close this issue but please feel free to raise any new issues with the rtmp-changes branch!
