### ISSUE TITLE
Server - New Player Creation Fails

### ISSUE THREAD

**Issue by radiorob** [openbroadcaster/obplayer#6]
Not creating new password

The work around must enter and save, password twice when provisioning and adding New Player for first time authentication

**Comment by geoplanet** [comment]
Cannot reproduce using Server/testing and Player/master.
Able to define new Player with password in a single operation and connect to new Player using defined password. 
The logged query:
INSERT INTO `devices` SET `name`="PwdTst", `description`="Password Bugtest", `stream_url`="", `password`="$2y$10$WAL2wfOGsKeX0Zw0PohBg.NSbtNcPRS..uYB.T97nGs.wagik35Qi", `ip_address`="", `support_audio`="1", `support_video`="", `support_images`="", `support_linein`="", `timezone`="Kwajalein", `station_id_image_duration`="15", `default_playlist_id`="", `parent_device_id`=NULL, `use_parent_dynamic`=0, `use_parent_schedule`=0, `use_parent_ids`=0, `use_parent_playlist`=0, `use_parent_emergency`=0, `owner_id`="1"

**Comment by geoplanet** [comment]
This issue was moved to openbroadcaster/Server#13
