### ISSUE TITLE
OBPlayer not resuming videos on restart

### ISSUE THREAD

**Issue by alphabitnz** [openbroadcaster/obplayer#72]
When OBPlayer gets restarted, the log says it's attempting to resume the last video name from x seconds, but the player stays blank until that video was scheduled to end then begins playing the next video correctly.

A previous player version I was running would instead play the video it was trying to resume but from the beginning, and then hard cut to the next video at the point a correctly resumed video would have finished.

Ideally resume should work as intended rather than either of these behaviours.

**Comment by radiorob** [comment]
Can confirm everything plays back at the correct times after a player restart for a media item and playlist, but only seen this working for audio. Have come across this issue with video before.  Does it behave this way with Theora or image slide show?

**Comment by alphabitnz** [comment]
It's a weird one. with current (RTMP Testing) build I have seen occasions where it resumes the file from 0 seconds and cuts off where it would have ended if resumed correctly, occasions where it plays the first frame of the video and then goes black, and possibly one time it actually resumed correctly.

I do agree this is bug is probably specific to the video pipe code, and I think the whole pipeline needs a rewrite - especially if it's ever using the gstreamer videomixer element which is basically deprecated and unmaintained now - superseded by the compositor element.
Since implementing my load tweak video pipe properties I have been getting walls and walls of a buffer error message that hints at videomixer being involved?

**Comment by vincentthedev** [comment]
This is a issue I've seen in audio playback as well. I'll look in to this and report back here,

**Comment by alphabitnz** [comment]
Just an update on this issue - problem seems to have gone away after enabling Icecast streaming outputs (in addition to the YouTube/RTMP stream outs).

If it's relevant, two Icecast streaming outputs are being sent (one to external relay and other to localhost).
