### ISSUE TITLE
Player crashes outputing video on Wayland

### ISSUE THREAD

**Issue by vincentthedev** [openbroadcaster/obplayer#74]
**Describe the bug**
If the player is running under a Wayland session and playing video it will fail to start.

**To Reproduce**
1. Enable video output to the desktop under the web UI output's tab.
2. Save & restart

**Expected behavior**
The player should not fail to start on Wayland sessions when playing video.

**Desktop:**
 - OS: Ubuntu 20.04
 - Browser Firefox
 - Version 100

**Additional context**
Git Branch: Develop
Version: 5.1.0-20210315
```
[May 26 2022 12:56:11 UTC] [error] Traceback (most recent call last):
  File "/home/vincentmaggard/Documents/Git/obplayer/obplayer/main.py", line 78, in start
    obplayer.Gui.create_window()
  File "/home/vincentmaggard/Documents/Git/obplayer/obplayer/gui.py", line 84, in create_window
    self.gst_xid = self.gui_gst_area.get_window().get_xid()
AttributeError: 'GdkWaylandWindow' object has no attribute 'get_xid'
```

**Comment by vincentthedev** [comment]
Upon doing some research the needed for our playback and overlay support isn't in python yet and until it all player video sessions need to be under X11. Code was added to the python, and bash code to ensure the player will start under X11 even if the player was started by a user that was under Wayland. If you have any updates on this please include them. This issue will remain until a full fix is found for the Wayland issue.

**Comment by radiorob** [comment]
user reporting 20.04 lts wayland desktop and player 5.2-develop set as video mode wayland working without screen tearing issue
