### ISSUE TITLE
No video, only black without a desktop

### ISSUE THREAD

**Issue by JJK1231** [openbroadcaster/obplayer#78]
Hi, I have everything set up but I am not getting any video in a stream. I can hear the audio, but see no video. How is that possible? I have an ubuntu server with no GUI.

Create a stream on YouTube, via rtsp or Icecast and then you don't see any video. Only black, but with sound.

Can somebody help me?

Thanks!

**Comment by vincentthedev** [comment]
This is a know issue to be fixed. If you run the player without a desktop and outputting video to the desktop then the video feed is blank on all the streams. There seem to be issues deep in the player back-end code that seems to be related, and I've been trying to track them down. Please stay tuned to this issue as I will update once I have a fix.
Thanks!

**Comment by radiorob** [comment]
https://github.com/openbroadcaster/obplayer/releases/tag/5.3.0

Send 1080 video from a headless player to icecast server.  There are also new RTMP Streaming tools

![image](https://github.com/user-attachments/assets/8d1f49c9-2065-49cb-aea6-00fdc757f1c5)
