### ISSUE TITLE
Installation obplayer_check error

### ISSUE THREAD

**Issue by tsyuha** [openbroadcaster/obplayer#79]
Hello all
I'm trying to install obplayer on my ubuntu 18.04. All dependencies from dependencies.txt were installed successfully but when I try to make step

2. Run bash "obplayer_check" or bash "obplayer_loop -f". "bash obplayer_check -h" for help

I receive error like

bash ./obplayer_check
Traceback (most recent call last):
  File "obplayer.py", line 25, in <module>
    obplayer.main()
  File "/ts/obplayer/obplayer/__init__.py", line 40, in main
    ObMainApp().start()
  File "/ts/obplayer/obplayer/main.py", line 63, in __init__
    obplayer.Config = obplayer.ObConfigData()
  File "/ts/obplayer/obplayer/data.py", line 159, in __init__
    self.check_defaults()
  File "/ts/obplayer/obplayer/data.py", line 479, in check_defaults
    tos_text = file.read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 497: ordinal not in range(128)

Please help what must I do to fix this problem
Best regards

**Comment by tsyuha** [comment]
If I try use 2 commands

export LC_CTYPE=en_US.UTF-8
bash "obplayer_check"

the script executes and shuts down without messages to the console, port 23233 is not opened.
Please help

**Comment by vincentthedev** [comment]
Can you please provide the branch you are running? You can paste the output of the `git status` command in your reply if needed. You will need to run the command in the same folder as the player is located in.

Thanks!

**Comment by sankamaduranga** [comment]
dear sir how to install this on on my vps can i give that commands

**Comment by radiorob** [comment]
Might try installing player code to /user/share/obplayer then cd to  /user/share/obplayer and then run "bash obplayer_check"
