### ISSUE TITLE
python3 maxing out CPUs when WebUI Open.

### ISSUE THREAD

**Issue by UberPlexCa** [openbroadcaster/obplayer#81]
**Describe the bug**
Brand new install of  Version | v5.1.1-20220603 main on Ubuntu Server 22.04.1
When you open the WebUI Python3 maxes out all CPUs on the thin client I use for alerts. The moment you close the browser CPUs go back to normal.  I believe others have seen this issue as well.
The browser is Chrome.

Any tweaks that can be made to fix this?  The thin client is a perfect box for the alerts it has no moving parts but it is CPU limited.

WebUI Open:
![image](https://user-images.githubusercontent.com/66147998/187031952-b20b7cf1-c4e5-4833-93b6-3e086e246591.png)

WebUI Closed:
![image](https://user-images.githubusercontent.com/66147998/187031964-df11867b-1e90-4f33-8bd6-34c8c2234b51.png)

Logs show this each time you open the WebUI

BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
Exception occurred during processing of request from ('192.168.1.20', 24843)
Traceback (most recent call last):
  File "/usr/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.10/http/server.py", line 425, in handle
    self.handle_one_request()
  File "/usr/lib/python3.10/http/server.py", line 413, in handle_one_request
    method()
  File "/root/obplayer/obplayer/httpadmin/httpserver.py", line 262, in do_POST
    self.send_content(response.status, response.mimetype, response.content, headers=response.headers)
  File "/root/obplayer/obplayer/httpadmin/httpserver.py", line 178, in send_content
    self.wfile.write(content)
  File "/usr/lib/python3.10/socketserver.py", line 826, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by JayManCanada6014** [comment]
Any update to this?

**Comment by radiorob** [comment]
I have also encountered this, especially trying to host multiple players on one VPS.  it is to do with the dated architecture of the way it displays http interface when it was created years ago.  @vincentthedev has started updating support for bootstrap themes that can be seen at the [beta demo site](http://eng.beta.player.openbroadcaster.pro/) and from the code on the testing branch.

**Comment by radiorob** [comment]
Tested this running on Raspberry Pi 5 with multiple browser windows open.  Many memory leaks patched in this release.

https://github.com/openbroadcaster/obplayer/releases/tag/5.3.0
