### ISSUE TITLE
Alert Tones

### ISSUE THREAD

**Issue by DaRealDingbat** [openbroadcaster/obplayer#82]
I was rummaging through the source files and found that the only alert tone provided is for Canada. How to I change it to the USA?

**Comment by JayManCanada6014** [comment]
> I was rummaging through the source files and found that the only alert tone provided is for Canada. How to I change it to the USA?

attention-signal.ogg  is the USA one.    Under  obplayer/obplayer/alerts/data   Thats the standard 1050mhz tone.

**Comment by radiorob** [comment]
Cool. Thanks @JayManCanada6014 I learned something about this project I DID NOT KNOW about
