### ISSUE TITLE
new install and couldn't get project to load

### ISSUE THREAD

**Issue by SpudGunMan** [openbroadcaster/obplayer#85]
**Describe the bug**
new install notes to share couldn't run project as stand alone either

```
Traceback (most recent call last):
  File "obplayer.py", line 25, in <module>
    obplayer.main()
  File "/home/user1/Desktop/bapi/test/obplayer/obplayer/__init__.py", line 40, in main
    ObMainApp().start()
  File "/home/user1/Desktop/bapi/test/obplayer/obplayer/main.py", line 63, in __init__
    obplayer.Config = obplayer.ObConfigData()
  File "/home/user1/Desktop/bapi/test/obplayer/obplayer/data.py", line 196, in __init__
    os.kill(os.getpid(), signal.SIGINT)
KeyboardInterrupt

```
puts us back at password problems?

```
     if password_system_move:
            obplayer.Log.log(message="Your player has moved from the old password system. Your passwods for the\
                                        readonly and admin users have been reset to the defaults. Your player will now restart.", mtype='config')
            os.kill(os.getpid(), signal.SIGINT)
```

**To Reproduce**
clone this project into 20.04 ubuntu 
follow directions for depends and found one more needed if wanted for documentation
`sudo pip3 install apsw`

`$python3 obplayer.py`

**Expected behavior**
project to open

**Screenshots**
cant attach here

**Desktop (please complete the following information):**
new  clean OS on VM

**Comment by radiorob** [comment]
python3-apsw in the dependencies.txt file.  @vincentthedev do we need to add?  pip3 install apsw

**Comment by vincentthedev** [comment]
You can install it via ```sudo apt install python3-apsw``` in Ubuntu. Also, I seen you removed other needed dependencies from dependencies.txt

**Comment by vincentthedev** [comment]
A pip install should also work too.

**Comment by radiorob** [comment]
meant to only change formatting and not delete anything, please revert if I goofed.  Which is it, python3-apsw or  pip3 install apsw  or are these separate packages and functions that are both required?

**Comment by vincentthedev** [comment]
They both install the same package just from pip, or the OS repos. The should use one. Must of the packages listed are apt unless pip is listed. In that case it's because of the lack of a Ubuntu apt(officially term deb package) package.
