### ISSUE TITLE
Server - - Advanced search displays zero results

### ISSUE THREAD

**Issue by radiorob** [openbroadcaster/obplayer#9]
- Advanced search with multiple genres displays zero results. Should produce a mix of results

**Comment by geoplanet** [comment]
I believe the nested "if" statements are connected with an "AND" query operator. Unless tracks have ALL characteristics to satisfy query, they wouldn't be returned. Need to have an operator ('AND','OR",'XOR') on the query.

**Comment by geoplanet** [comment]
This issue was moved to openbroadcaster/Server#12
